name: lingsuhealth-backend
services:
  - name: backend
    type: web
    ports:
      - port: 8080
        protocol: http
    build:
      type: docker
      dockerfile: Dockerfile
    env:
      - name: PORT
        value: "8080"
      - name: DEEPSEEK_API_KEY
        value: sk-b0b4f0292f8848c483ec8e1a847c6766
    health_check:
      http:
        path: /actuator/health
        port: 8080
    regions:
      - sin
    instance_type: free
